services:
  app:
    build:
      context: .
      target: production
      args:
        VITE_APP_FIREBASE_API_KEY: ${VITE_APP_FIREBASE_API_KEY}
        VITE_APP_AUTH_DOMAIN: ${VITE_APP_AUTH_DOMAIN}
        VITE_APP_FIREBASE_PROJECT_ID: ${VITE_APP_FIREBASE_PROJECT_ID}
        VITE_APP_FIREBASE_STORAGE_BUCKET: ${VITE_APP_FIREBASE_STORAGE_BUCKET}
        VITE_APP_FIREBASE_MESSAGING_SENDER_ID: ${VITE_APP_FIREBASE_MESSAGING_SENDER_ID}
        VITE_APP_FIREBASE_APP_ID: ${VITE_APP_FIREBASE_APP_ID}
        VITE_APP_FIREBASE_MEASUREMENTID: ${VITE_APP_FIREBASE_MEASUREMENTID}
        VITE_APP_DATABASE_URL: ${VITE_APP_DATABASE_URL}
        VITE_APP_FIREBASE_FCM_VAPID_KEY: ${VITE_APP_FIREBASE_FCM_VAPID_KEY}
        VITE_APP_USE_EMULATOR: "false"
    ports:
      - "3000:3000"
    restart: unless-stopped