services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
      - 5001:5001
      - 9000:9000
      - 8080:8080
      - 8085:8085
      - 5000:5000
      - 4000:4000
      - 9199:9199
      - 9099:9099
      - 4400:4400
    volumes:
      - .:/app
      - /app/node_modules
      - /app/functions/node_modules
      - /app/scripts
