FROM node:20-slim

# Set the working directory in the container
WORKDIR /app

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends openjdk-17-jre-headless bash && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g firebase-tools@11

# Pre-download emulators
RUN firebase setup:emulators:firestore && \
    firebase setup:emulators:storage && \
    firebase setup:emulators:database && \
    firebase setup:emulators:pubsub && \
    firebase setup:emulators:ui

# Copy package.json and package-lock.json to the container
COPY package*.json ./
COPY ./functions/package*.json ./functions/

# Install the project dependencies (skip husky in Docker)
RUN npm install --legacy-peer-deps --ignore-scripts

WORKDIR /app/functions
RUN npm install --legacy-peer-deps --ignore-scripts
WORKDIR /app

# Copy the entire project directory to the container
COPY . .

# Expose the desired port for the Node.js server
EXPOSE 5173
EXPOSE 4000
EXPOSE 5000
EXPOSE 5001
EXPOSE 8080
EXPOSE 9000
EXPOSE 8085
EXPOSE 9099
EXPOSE 9199
EXPOSE 4400

RUN chmod +x ./scripts/entrypoint.sh

CMD ["/app/scripts/entrypoint.sh"]
