name: Cypress End-to-End Tests

on: pull_request

permissions:
  contents: read

jobs:
  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [18]

    env:
      CI: false
      VITE_APP_FIREBASE_USE_EMULATOR: true

      VITE_APP_FIREBASE_API_KEY: ${{ vars.VITE_APP_FIREBASE_API_KEY }}
      VITE_APP_FIREBASE_AUTH_DOMAIN: ${{ vars.VITE_APP_FIREBASE_AUTH_DOMAIN }}
      VITE_APP_FIREBASE_DATABASE_URL: ${{ vars.VITE_APP_FIREBASE_DATABASE_URL }}
      VITE_APP_FIREBASE_PROJECT_ID: ${{ vars.VITE_APP_FIREBASE_PROJECT_ID }}
      VITE_APP_FIREBASE_STORAGE_BUCKET: ${{ vars.VITE_APP_FIREBASE_STORAGE_BUCKET }}
      VITE_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ vars.VITE_APP_FIREBASE_MESSAGING_SENDER_ID }}
      VITE_APP_FIREBASE_APP_ID: ${{ vars.VITE_APP_FIREBASE_APP_ID }}
      VITE_APP_FIREBASE_MEASUREMENTID: ${{ vars.VITE_APP_FIREBASE_MEASUREMENTID }}
      VITE_APP_FIREBASE_FCM_VAPID_KEY: ${{ vars.VITE_APP_FIREBASE_FCM_VAPID_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}-

      - name: Install Functions Dependencies
        run: npm install --legacy-peer-deps
        working-directory: functions

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Start Firebase Emulators
        run: |
          firebase emulators:start \
            --import=./testdata \
            --project "$VITE_APP_FIREBASE_PROJECT_ID" &
            sleep 15

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config-file: cypress.config.js
          install-command: npm install --legacy-peer-deps
          build: npm run build
          start: npm run dev
          wait-on: "http://localhost:5173"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ vars.CYPRESS_PROJECT_ID }}
          COMMIT_INFO_BRANCH: ${{ github.ref_name }}
